jobs:
  include:
    - if: branch = main
      env: VERSION=6.0.0-SNAPSHOT

services:
  - docker

script:
  # get the webapp.war
  mvn dependency:copy -Dartifact=org.fcrepo:fcrepo-webapp:$VERSION:war -DoutputDirectory=. -Dmdep.stripVersion=true

deploy:
  skip_cleanup: true
  - provider: script
    script: ./build-and-push-to-dockerhub.sh ./fcrepo-webapp.war $VERSION
    on:
      repo: fcrepo-exts/fcrepo-docker
      condition: ${TRAVIS_BRANCH} == *-maintenance
  - provider: script
    script: ./build-and-push-to-dockerhub.sh ./fcrepo-webapp.war $VERSION latest
    on:
      repo: fcrepo-exts/fcrepo-docker
      branch: main
